"""add perfis permissoes colaborador_equipes

Revision ID: 128a77581e33
Revises: 696c236ac672
Create Date: 2026-07-01 23:10:59.990247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128a77581e33'
down_revision = '696c236ac672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.SmallInteger(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('permissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('modulo', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('perfil_permissoes',
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissoes.id'], ),
    sa.PrimaryKeyConstraint('perfil_id', 'permissao_id')
    )
    op.create_table('colaborador_equipes',
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.PrimaryKeyConstraint('colaborador_id', 'equipe_id')
    )
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'perfis', ['perfil_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('perfil_id')

    op.drop_table('colaborador_equipes')
    op.drop_table('perfil_permissoes')
    op.drop_table('permissoes')
    op.drop_table('perfis')
    # ### end Alembic commands ###
