"""initial

Revision ID: 56a4623667a2
Revises: 
Create Date: 2026-06-27 17:55:10.448917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a4623667a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colaboradores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('data_admissao', sa.Date(), nullable=False),
    sa.Column('funcao', sa.String(length=100), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('perfil', sa.Enum('colaborador', 'gestor', 'rh', 'diretoria'), nullable=False),
    sa.Column('ad_login', sa.String(length=150), nullable=True),
    sa.Column('ativo', sa.SmallInteger(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.ForeignKeyConstraint(['gestor_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dayoff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('data_solicitada', sa.Date(), nullable=False),
    sa.Column('mes_referencia', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('aguardando_gestor', 'aprovado', 'reprovado', 'cancelado'), nullable=False),
    sa.Column('comentario_gestor', sa.Text(), nullable=True),
    sa.Column('decidido_em', sa.DateTime(), nullable=True),
    sa.Column('solicitado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('lida', sa.SmallInteger(), nullable=False),
    sa.Column('enviado_email', sa.SmallInteger(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodos_aquisitivos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('dias_direito', sa.Integer(), nullable=False),
    sa.Column('data_limite_saida', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ferias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('periodo_aquisitivo_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('data_retorno', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('aguardando_gestor', 'aguardando_rh', 'aprovada', 'reprovada', 'cancelada'), nullable=False),
    sa.Column('comentario_gestor', sa.Text(), nullable=True),
    sa.Column('comentario_rh', sa.Text(), nullable=True),
    sa.Column('aprovado_gestor_em', sa.DateTime(), nullable=True),
    sa.Column('aprovado_rh_em', sa.DateTime(), nullable=True),
    sa.Column('solicitado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['periodo_aquisitivo_id'], ['periodos_aquisitivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ferias')
    op.drop_table('periodos_aquisitivos')
    op.drop_table('notificacoes')
    op.drop_table('dayoff')
    op.drop_table('colaboradores')
    op.drop_table('equipes')
    # ### end Alembic commands ###
