"""add foto_path colaborador

Revision ID: 696c236ac672
Revises: d05e996ddbbe
Create Date: 2026-07-01 22:30:11.140722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696c236ac672'
down_revision = 'd05e996ddbbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_column('foto_path')

    # ### end Alembic commands ###
