"""add funcoes table

Revision ID: d05e996ddbbe
Revises: 56a4623667a2
Create Date: 2026-06-30 00:41:49.244806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05e996ddbbe'
down_revision = '56a4623667a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funcao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'funcoes', ['funcao_id'], ['id'])

    with op.batch_alter_table('equipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.SmallInteger(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipes', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('funcao_id')

    op.drop_table('funcoes')
    # ### end Alembic commands ###
